version: '3'
services:
  back-end-prod:
    container_name: prod-100ty-backend
    image: ${IMAGE_APP_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_ENVIROMENT: prod
      PORT: 9000
      CLIENT_URL: http://localhost:3000
      DATABASE_TYPE: postgres
      DATABASE_HOST: PostgreSQL
      DATABASE_PORT: 5432
      DATABASE_NAME: 100ty
      DATABASE_USERNAME: agen138
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE_IN: 7d
      CLOUDINARY_NAME: dcnsjrkks
      CLOUDINARY_API_KEY: 276681834787759
      CLOUDINARY_API_SECRET: EyOssITM4DOr0Fn96CXBhoqWk4s
    ports:
      - "5336:9000"
    restart: always
    networks:
      - 100ty

networks:
  100ty:
    external: true
