import { RoleData, RoleId, RoleName } from '../interface';

export const SuperAdminPermissionData = [
  {
    id: 1,
    icon: 'ion:home-outline',
    name: 'Trang chủ',
    type: 'MENU',
    label: 'Trang chủ',
    order: 1,
    route: 'trang-chu',
    parentId: '',
    component: '/sys/trang-chu/index.tsx',
  },
  {
    id: 2,
    icon: 'fa6-solid:sack-dollar',
    name: 'Thu họ',
    type: 'MENU',
    label: 'Thu họ',
    order: 2,
    route: 'thu-ho',
    parentId: '',
    component: '/sys/thu-ho/index.tsx',
  },
  {
    id: 5,
    icon: 'akar-icons:money',
    name: 'Giao việc cho cửa hàng',
    type: 'MENU',
    label: 'Giao việc cho cửa hàng',
    order: '5',
    route: 'giao-viec-cho-cua-hang',
    parentId: '',
    component: '/sys/giao-viec-cho-cua-hang/index.tsx',
  },
  {
    id: 9,
    icon: 'fluent:people-money-20-filled',
    name: 'Quản lý khách hàng',
    type: 'CATALOGUE',
    label: 'Quản lý khách hàng',
    order: 9,
    route: 'quan-ly-khach-hang',
    children: [
      {
        id: 91,
        name: 'Danh sách khách hàng',
        type: 'MENU',
        label: 'Danh sách khách hàng',
        route: 'danh-sach-khach-hang',
        parentId: 9,
        component: '/quan-ly-khach-hang/danh-sach-khach-hang/index.tsx',
      },
      {
        id: 92,
        name: 'Kiểm tra thông tin khách hàng',
        type: 'MENU',
        label: 'Kiểm tra thông tin khách hàng',
        route: 'kiem-tra-thong-tin-khach-hang',
        parentId: 9,
        component:
          '/quan-ly-khach-hang/kiem-tra-thong-tin-khach-hang/index.tsx',
      },
      {
        id: 9,
        name: 'Kiểm tra nợ xấu',
        type: 'MENU',
        label: 'Kiểm tra nợ xấu',
        route: 'kiem-tra-no-xau',
        parentId: 9,
        component: '/quan-ly-khach-hang/kiem-tra-no-xau/index.tsx',
      },
    ],
    parentId: '',
  },
  {
    id: 1000,
    icon: 'streamline:shopping-store-2-store-shop-shops-stores',
    name: 'Quản lý đa cửa hàng',
    type: 'CATALOGUE',
    label: 'Quản lý đa cửa hàng',
    order: 10,
    route: 'quan-ly-da-cua-hang',
    children: [
      {
        id: 10001,
        name: 'Danh sách cửa hàng',
        type: 'MENU',
        label: 'Danh sách cửa hàng',
        route: 'danh-sach-cua-hang',
        parentId: 1000,
        component: '/quan-ly-da-cua-hang/danh-sach-sua-hang/index.tsx',
      },
      {
        id: 10002,
        name: 'Tổng quát cửa hàng',
        type: 'MENU',
        label: 'Tổng quát cửa hàng',
        route: 'tong-quat-cua-hang',
        parentId: 1000,
        component: '/quan-ly-da-cua-hang/tong-quat-cua-hang/index.tsx',
      },
      {
        id: 10003,
        name: 'Chi tiết cửa hàng',
        type: 'MENU',
        label: 'Chi tiết cửa hàng',
        route: 'chi-tiet-cua-hang',
        parentId: 1000,
        component: '/quan-ly-da-cua-hang/chi-tiet-cua-hang/index.tsx',
      },
    ],
    parentId: '',
  },
  {
    id: 1200,
    icon: 'vaadin:money-exchange',
    name: 'Quản lý thu chi',
    type: 'CATALOGUE',
    label: 'Quản lý thu chi',
    order: '12',
    route: 'quan-ly-thu-chi',
    children: [
      {
        id: 12001,
        name: 'Thu/Chi hợp đồng',
        type: 'MENU',
        label: 'Thu/Chi hợp đồng',
        route: 'thu-chi-hop-dong',
        parentId: 1200,
        component: '/quan-ly-thu-chi/thu-chi-hop-dong/index.tsx',
      },
      {
        id: 12002,
        name: 'Thu/Chi ngoài lề',
        type: 'MENU',
        label: 'Thu/Chi ngoài lề',
        route: 'thu-chi-ngoai-le',
        parentId: 1200,
        component: '/quan-ly-thu-chi/thu-chi-ngoai-le/index.tsx',
      },
    ],
    parentId: '',
  },
  {
    id: 1300,
    icon: 'streamline:investment-selection',
    name: 'Quản lý nguồn vốn',
    type: 'MENU',
    label: 'Quản lý nguồn vốn',
    order: '13',
    route: 'quan-ly-nguon-von',
    parentId: '',
    component: '/sys/quan-ly-nguon-von/index.tsx',
  },
  {
    id: 1400,
    icon: 'akar-icons:statistic-up',
    name: 'Thống kê',
    type: 'CATALOGUE',
    label: 'Thống kê',
    order: '14',
    route: 'thong-ke',
    children: [
      {
        id: 14001,
        name: 'Thu dự kiến',
        type: 'MENU',
        label: 'Thu dự kiến',
        route: 'thu-du-kien',
        parentId: 1400,
        component: '/thong-ke/thu-du-kien/index.tsx',
      },
      {
        id: 14002,
        name: 'Thu',
        type: 'MENU',
        label: 'Thu',
        route: 'thu',
        parentId: 1400,
        component: '/thong-ke/thu/index.tsx',
      },
      {
        id: 14003,
        name: 'Chi',
        type: 'MENU',
        label: 'Chi',
        route: 'chi',
        parentId: 1400,
        component: '/thong-ke/chi/index.tsx',
      },
      {
        id: 14004,
        name: 'Tin nhắn đã gửi',
        type: 'MENU',
        label: 'Tin nhắn đã gửi',
        route: 'tin-nhan-da-gui',
        parentId: 1400,
        component: '/thong-ke/tin-nhan-da-gui/index.tsx',
      },
      {
        id: 14005,
        name: 'Email đã gửi',
        type: 'MENU',
        label: 'Email đã gửi',
        route: 'email-da-gui',
        parentId: 1400,
        component: '/thong-ke/email-da-gui/index.tsx',
      },
      {
        id: 14006,
        name: 'Danh sách hợp đồng bị xóa',
        type: 'MENU',
        label: 'Danh sách hợp đồng bị xóa',
        route: 'danh-sach-hop-dong-bi-xoa',
        parentId: 1400,
        component: '/thong-ke/danh-sach-hop-dong-bi-xoa/index.tsx',
      },
      {
        id: 14007,
        name: 'Danh sách thu bị xóa',
        type: 'MENU',
        label: 'Danh sách thu bị xóa',
        route: 'danh-sach-thu-bi-xoa',
        parentId: 1400,
        component: '/thong-ke/danh-sach-thu-bi-xoa/index.tsx',
      },
      {
        id: 14008,
        name: 'Danh sách chi bị xóa',
        type: 'MENU',
        label: 'Danh sách chi bị xóa',
        route: 'danh-sach-chi-bi-xoa',
        parentId: 1400,
        component: '/thong-ke/danh-sach-chi-bi-xoa/index.tsx',
      },
    ],
    parentId: '',
  },
  {
    id: 1500,
    icon: 'tabler:report',
    name: 'Báo cáo',
    type: 'CATALOGUE',
    label: 'Báo cáo',
    order: '15',
    route: 'bao-cao',
    children: [
      {
        id: 15001,
        name: 'Dòng tiền',
        type: 'MENU',
        label: 'Dòng tiền',
        route: 'dong-tien',
        parentId: 1500,
        component: '/bao-cao/dong-tien/index.tsx',
      },
      {
        id: 15002,
        name: 'Lợi nhuận',
        type: 'MENU',
        label: 'Lợi nhuận',
        route: 'loi-nhuan',
        parentId: 1500,
        component: '/bao-cao/loi-nhuan/index.tsx',
      },
      {
        id: 15003,
        name: 'Dư nợ cho vay',
        type: 'MENU',
        label: 'Dư nợ cho vay',
        route: 'du-no-cho-vay',
        parentId: 1500,
        component: '/bao-cao/du-no-cho-vay/index.tsx',
      },
      {
        id: 15004,
        name: 'Dư nợ nhận vay',
        type: 'MENU',
        label: 'Dư nợ nhận vay',
        route: 'du-no-nhan-vay',
        parentId: 1500,
        component: '/bao-cao/du-no-nhan-vay/index.tsx',
      },
      {
        id: 15005,
        name: 'Dư nợ giao nhân viên',
        type: 'MENU',
        label: 'Dư nợ giao nhân viên',
        route: 'du-no-giao-nhan-vien',
        parentId: 1500,
        component: '/bao-cao/du-no-giao-nhan-vien/index.tsx',
      },
      {
        id: 15006,
        name: 'Hợp đồng chờ duyệt',
        type: 'MENU',
        label: 'Hợp đồng chờ duyệt',
        route: 'hop-dong-cho-duyet',
        parentId: 1500,
        component: '/bao-cao/hop-dong-cho-duyet/index.tsx',
      },
      {
        id: 15007,
        name: 'Giao dịch trong ngày',
        type: 'MENU',
        label: 'Giao dịch trong ngày',
        route: 'giao-dich-trong-ngay',
        parentId: 1500,
        component: '/bao-cao/giao-dich-trong-ngay/index.tsx',
      },
      {
        id: 15008,
        name: 'Giao dịch chờ duyệt',
        type: 'MENU',
        label: 'Giao dịch chờ duyệt',
        route: 'giao-dich-cho-duyet',
        parentId: 1500,
        component: '/bao-cao/giao-dich-cho-duyet/index.tsx',
      },
      {
        id: 15009,
        name: 'Kiểm kê quỹ',
        type: 'MENU',
        label: 'Kiểm kê quỹ',
        route: 'kiem-ke-quy',
        parentId: 1500,
        component: '/bao-cao/kiem-ke-quy/index.tsx',
      },
    ],
    parentId: '',
  },
  {
    id: 1600,
    icon: 'icon-park-solid:system',
    name: 'Quản trị hệ thống',
    type: 'CATALOGUE',
    label: 'Quản trị hệ thống',
    order: '16',
    route: 'quan-tri-he-thong',
    children: [
      {
        id: 16001,
        name: 'Thiết lập thiết bị',
        type: 'MENU',
        label: 'Thiết lập thiết bị',
        route: 'cau-hinh-tai-san',
        parentId: 1600,
        component: '/quan-tri-he-thong/cau-hinh-tai-san/index.tsx',
      },
      {
        id: 16002,
        name: 'Thiết lập máy chủ',
        type: 'MENU',
        label: 'Thiết lập máy chủ',
        route: 'cau-hinh-tinh-lai',
        parentId: 1600,
        component: '/quan-tri-he-thong/cau-hinh-tinh-lai/index.tsx',
      },
      {
        id: 16003,
        name: 'Loại phiếu thu chi',
        type: 'MENU',
        label: 'Loại phiếu thu chi',
        route: 'loai-phieu-thu-chi',
        parentId: 1600,
        component: '/quan-tri-he-thong/loai-phieu-thu-chi/index.tsx',
      },
      {
        id: 16004,
        name: 'Cấu hình email',
        type: 'MENU',
        label: 'Cấu hình email',
        route: 'cau-hinh-email',
        parentId: 1600,
        component: '/quan-tri-he-thong/cau-hinh-email/index.tsx',
      },
      {
        id: 16005,
        name: 'Cấu hình hệ thống',
        type: 'MENU',
        label: 'Cấu hình hệ thống',
        route: 'cau-hinh-he-thong',
        parentId: 1600,
        component: '/quan-tri-he-thong/cau-hinh-he-thong/index.tsx',
      },
      {
        id: 16006,
        name: 'Quản lý log',
        type: 'MENU',
        label: 'Quản lý log',
        route: 'quan-ly-log',
        parentId: 1600,
        component: '/quan-tri-he-thong/quan-ly-log/index.tsx',
      },
      {
        id: 16007,
        name: 'Quản lý mẫu hợp đồng',
        type: 'MENU',
        label: 'Quản lý mẫu hợp đồng',
        route: 'quan-ly-mau-hop-dong',
        parentId: 1600,
        component: '/quan-tri-he-thong/quan-ly-mau-hop-dong/index.tsx',
      },
      {
        id: 16008,
        name: 'Quản lý mẫu thu chi',
        type: 'MENU',
        label: 'Quản lý mẫu thu chi',
        route: 'quan-ly-mau-thu-chi',
        parentId: 1600,
        component: '/quan-tri-he-thong/quan-ly-mau-thu-chi/index.tsx',
      },
      {
        id: 16009,
        name: 'Bảo trì dữ liệu',
        type: 'MENU',
        label: 'Bảo trì dữ liệu',
        route: 'bao-tri-du-lieu',
        parentId: 1600,
        component: '/quan-tri-he-thong/bao-tri-du-lieu/index.tsx',
      },
      {
        id: 16010,
        name: 'Thông báo',
        type: 'MENU',
        label: 'Thông báo',
        route: 'thong-bao',
        parentId: 1600,
        component: '/quan-tri-he-thong/thong-bao/index.tsx',
      },
      {
        id: 16011,
        name: 'Menu',
        type: 'MENU',
        label: 'Menu',
        route: 'menu',
        parentId: 1600,
        component: '/quan-tri-he-thong/menu/index.tsx',
      },
    ],
    parentId: '',
  },
];

export const AdminPermissionData = [
  {
    id: 1,
    icon: 'ion:home-outline',
    name: 'Trang chủ',
    type: 'MENU',
    label: 'Trang chủ',
    order: 1,
    route: 'trang-chu',
    parentId: '',
    component: '/sys/trang-chu/index.tsx',
  },
  {
    id: 2,
    icon: 'fa6-solid:sack-dollar',
    name: 'Thu họ',
    type: 'MENU',
    label: 'Thu họ',
    order: 2,
    route: 'thu-ho',
    parentId: '',
    component: '/sys/thu-ho/index.tsx',
  },
  {
    id: 5,
    icon: 'akar-icons:money',
    name: 'Giao việc cho cửa hàng',
    type: 'MENU',
    label: 'Giao việc cho cửa hàng',
    order: '5',
    route: 'giao-viec-cho-cua-hang',
    parentId: '',
    component: '/sys/giao-viec-cho-cua-hang/index.tsx',
  },
  {
    id: 9,
    icon: 'fluent:people-money-20-filled',
    name: 'Quản lý khách hàng',
    type: 'CATALOGUE',
    label: 'Quản lý khách hàng',
    order: 9,
    route: 'quan-ly-khach-hang',
    children: [
      {
        id: 91,
        name: 'Danh sách khách hàng',
        type: 'MENU',
        label: 'Danh sách khách hàng',
        route: 'danh-sach-khach-hang',
        parentId: 9,
        component: '/quan-ly-khach-hang/danh-sach-khach-hang/index.tsx',
      },
      {
        id: 92,
        name: 'Kiểm tra thông tin khách hàng',
        type: 'MENU',
        label: 'Kiểm tra thông tin khách hàng',
        route: 'kiem-tra-thong-tin-khach-hang',
        parentId: 9,
        component:
          '/quan-ly-khach-hang/kiem-tra-thong-tin-khach-hang/index.tsx',
      },
      {
        id: 9,
        name: 'Kiểm tra nợ xấu',
        type: 'MENU',
        label: 'Kiểm tra nợ xấu',
        route: 'kiem-tra-no-xau',
        parentId: 9,
        component: '/quan-ly-khach-hang/kiem-tra-no-xau/index.tsx',
      },
    ],
    parentId: '',
  },
  {
    id: 1000,
    icon: 'streamline:shopping-store-2-store-shop-shops-stores',
    name: 'Quản lý đa cửa hàng',
    type: 'CATALOGUE',
    label: 'Quản lý đa cửa hàng',
    order: 10,
    route: 'quan-ly-da-cua-hang',
    children: [
      {
        id: 10001,
        name: 'Danh sách cửa hàng',
        type: 'MENU',
        label: 'Danh sách cửa hàng',
        route: 'danh-sach-cua-hang',
        parentId: 1000,
        component: '/quan-ly-da-cua-hang/danh-sach-sua-hang/index.tsx',
      },
      {
        id: 10002,
        name: 'Tổng quát cửa hàng',
        type: 'MENU',
        label: 'Tổng quát cửa hàng',
        route: 'tong-quat-cua-hang',
        parentId: 1000,
        component: '/quan-ly-da-cua-hang/tong-quat-cua-hang/index.tsx',
      },
      {
        id: 10003,
        name: 'Chi tiết cửa hàng',
        type: 'MENU',
        label: 'Chi tiết cửa hàng',
        route: 'chi-tiet-cua-hang',
        parentId: 1000,
        component: '/quan-ly-da-cua-hang/chi-tiet-cua-hang/index.tsx',
      },
    ],
    parentId: '',
  },
  {
    id: 1200,
    icon: 'vaadin:money-exchange',
    name: 'Quản lý thu chi',
    type: 'CATALOGUE',
    label: 'Quản lý thu chi',
    order: '12',
    route: 'quan-ly-thu-chi',
    children: [
      {
        id: 12001,
        name: 'Thu/Chi hợp đồng',
        type: 'MENU',
        label: 'Thu/Chi hợp đồng',
        route: 'thu-chi-hop-dong',
        parentId: 1200,
        component: '/quan-ly-thu-chi/thu-chi-hop-dong/index.tsx',
      },
      {
        id: 12002,
        name: 'Thu/Chi ngoài lề',
        type: 'MENU',
        label: 'Thu/Chi ngoài lề',
        route: 'thu-chi-ngoai-le',
        parentId: 1200,
        component: '/quan-ly-thu-chi/thu-chi-ngoai-le/index.tsx',
      },
    ],
    parentId: '',
  },
  {
    id: 1300,
    icon: 'streamline:investment-selection',
    name: 'Quản lý nguồn vốn',
    type: 'MENU',
    label: 'Quản lý nguồn vốn',
    order: '13',
    route: 'quan-ly-nguon-von',
    parentId: '',
    component: '/sys/quan-ly-nguon-von/index.tsx',
  },
  {
    id: 1400,
    icon: 'akar-icons:statistic-up',
    name: 'Thống kê',
    type: 'CATALOGUE',
    label: 'Thống kê',
    order: '14',
    route: 'thong-ke',
    children: [
      {
        id: 14001,
        name: 'Thu dự kiến',
        type: 'MENU',
        label: 'Thu dự kiến',
        route: 'thu-du-kien',
        parentId: 1400,
        component: '/thong-ke/thu-du-kien/index.tsx',
      },
      {
        id: 14002,
        name: 'Thu',
        type: 'MENU',
        label: 'Thu',
        route: 'thu',
        parentId: 1400,
        component: '/thong-ke/thu/index.tsx',
      },
      {
        id: 14003,
        name: 'Chi',
        type: 'MENU',
        label: 'Chi',
        route: 'chi',
        parentId: 1400,
        component: '/thong-ke/chi/index.tsx',
      },
      {
        id: 14004,
        name: 'Tin nhắn đã gửi',
        type: 'MENU',
        label: 'Tin nhắn đã gửi',
        route: 'tin-nhan-da-gui',
        parentId: 1400,
        component: '/thong-ke/tin-nhan-da-gui/index.tsx',
      },
      {
        id: 14005,
        name: 'Email đã gửi',
        type: 'MENU',
        label: 'Email đã gửi',
        route: 'email-da-gui',
        parentId: 1400,
        component: '/thong-ke/email-da-gui/index.tsx',
      },
      {
        id: 14006,
        name: 'Danh sách hợp đồng bị xóa',
        type: 'MENU',
        label: 'Danh sách hợp đồng bị xóa',
        route: 'danh-sach-hop-dong-bi-xoa',
        parentId: 1400,
        component: '/thong-ke/danh-sach-hop-dong-bi-xoa/index.tsx',
      },
      {
        id: 14007,
        name: 'Danh sách thu bị xóa',
        type: 'MENU',
        label: 'Danh sách thu bị xóa',
        route: 'danh-sach-thu-bi-xoa',
        parentId: 1400,
        component: '/thong-ke/danh-sach-thu-bi-xoa/index.tsx',
      },
      {
        id: 14008,
        name: 'Danh sách chi bị xóa',
        type: 'MENU',
        label: 'Danh sách chi bị xóa',
        route: 'danh-sach-chi-bi-xoa',
        parentId: 1400,
        component: '/thong-ke/danh-sach-chi-bi-xoa/index.tsx',
      },
    ],
    parentId: '',
  },
  {
    id: 1500,
    icon: 'tabler:report',
    name: 'Báo cáo',
    type: 'CATALOGUE',
    label: 'Báo cáo',
    order: '15',
    route: 'bao-cao',
    children: [
      {
        id: 15001,
        name: 'Dòng tiền',
        type: 'MENU',
        label: 'Dòng tiền',
        route: 'dong-tien',
        parentId: 1500,
        component: '/bao-cao/dong-tien/index.tsx',
      },
      {
        id: 15002,
        name: 'Lợi nhuận',
        type: 'MENU',
        label: 'Lợi nhuận',
        route: 'loi-nhuan',
        parentId: 1500,
        component: '/bao-cao/loi-nhuan/index.tsx',
      },
      {
        id: 15003,
        name: 'Dư nợ cho vay',
        type: 'MENU',
        label: 'Dư nợ cho vay',
        route: 'du-no-cho-vay',
        parentId: 1500,
        component: '/bao-cao/du-no-cho-vay/index.tsx',
      },
      {
        id: 15004,
        name: 'Dư nợ nhận vay',
        type: 'MENU',
        label: 'Dư nợ nhận vay',
        route: 'du-no-nhan-vay',
        parentId: 1500,
        component: '/bao-cao/du-no-nhan-vay/index.tsx',
      },
      {
        id: 15005,
        name: 'Dư nợ giao nhân viên',
        type: 'MENU',
        label: 'Dư nợ giao nhân viên',
        route: 'du-no-giao-nhan-vien',
        parentId: 1500,
        component: '/bao-cao/du-no-giao-nhan-vien/index.tsx',
      },
      {
        id: 15006,
        name: 'Hợp đồng chờ duyệt',
        type: 'MENU',
        label: 'Hợp đồng chờ duyệt',
        route: 'hop-dong-cho-duyet',
        parentId: 1500,
        component: '/bao-cao/hop-dong-cho-duyet/index.tsx',
      },
      {
        id: 15007,
        name: 'Giao dịch trong ngày',
        type: 'MENU',
        label: 'Giao dịch trong ngày',
        route: 'giao-dich-trong-ngay',
        parentId: 1500,
        component: '/bao-cao/giao-dich-trong-ngay/index.tsx',
      },
      {
        id: 15008,
        name: 'Giao dịch chờ duyệt',
        type: 'MENU',
        label: 'Giao dịch chờ duyệt',
        route: 'giao-dich-cho-duyet',
        parentId: 1500,
        component: '/bao-cao/giao-dich-cho-duyet/index.tsx',
      },
      {
        id: 15009,
        name: 'Kiểm kê quỹ',
        type: 'MENU',
        label: 'Kiểm kê quỹ',
        route: 'kiem-ke-quy',
        parentId: 1500,
        component: '/bao-cao/kiem-ke-quy/index.tsx',
      },
    ],
    parentId: '',
  },
  {
    id: 1600,
    icon: 'icon-park-solid:system',
    name: 'Quản trị hệ thống',
    type: 'CATALOGUE',
    label: 'Quản trị hệ thống',
    order: '16',
    route: 'quan-tri-he-thong',
    children: [
      {
        id: 16001,
        name: 'Thiết lập thiết bị',
        type: 'MENU',
        label: 'Thiết lập thiết bị',
        route: 'cau-hinh-tai-san',
        parentId: 1600,
        component: '/quan-tri-he-thong/cau-hinh-tai-san/index.tsx',
      },
      {
        id: 16002,
        name: 'Thiết lập máy chủ',
        type: 'MENU',
        label: 'Thiết lập máy chủ',
        route: 'cau-hinh-tinh-lai',
        parentId: 1600,
        component: '/quan-tri-he-thong/cau-hinh-tinh-lai/index.tsx',
      },
      {
        id: 16003,
        name: 'Loại phiếu thu chi',
        type: 'MENU',
        label: 'Loại phiếu thu chi',
        route: 'loai-phieu-thu-chi',
        parentId: 1600,
        component: '/quan-tri-he-thong/loai-phieu-thu-chi/index.tsx',
      },
      {
        id: 16004,
        name: 'Cấu hình email',
        type: 'MENU',
        label: 'Cấu hình email',
        route: 'cau-hinh-email',
        parentId: 1600,
        component: '/quan-tri-he-thong/cau-hinh-email/index.tsx',
      },
      {
        id: 16005,
        name: 'Cấu hình hệ thống',
        type: 'MENU',
        label: 'Cấu hình hệ thống',
        route: 'cau-hinh-he-thong',
        parentId: 1600,
        component: '/quan-tri-he-thong/cau-hinh-he-thong/index.tsx',
      },
      {
        id: 16006,
        name: 'Quản lý log',
        type: 'MENU',
        label: 'Quản lý log',
        route: 'quan-ly-log',
        parentId: 1600,
        component: '/quan-tri-he-thong/quan-ly-log/index.tsx',
      },
      {
        id: 16007,
        name: 'Quản lý mẫu hợp đồng',
        type: 'MENU',
        label: 'Quản lý mẫu hợp đồng',
        route: 'quan-ly-mau-hop-dong',
        parentId: 1600,
        component: '/quan-tri-he-thong/quan-ly-mau-hop-dong/index.tsx',
      },
      {
        id: 16008,
        name: 'Quản lý mẫu thu chi',
        type: 'MENU',
        label: 'Quản lý mẫu thu chi',
        route: 'quan-ly-mau-thu-chi',
        parentId: 1600,
        component: '/quan-tri-he-thong/quan-ly-mau-thu-chi/index.tsx',
      },
      {
        id: 16009,
        name: 'Bảo trì dữ liệu',
        type: 'MENU',
        label: 'Bảo trì dữ liệu',
        route: 'bao-tri-du-lieu',
        parentId: 1600,
        component: '/quan-tri-he-thong/bao-tri-du-lieu/index.tsx',
      },
      {
        id: 16010,
        name: 'Thông báo',
        type: 'MENU',
        label: 'Thông báo',
        route: 'thong-bao',
        parentId: 1600,
        component: '/quan-tri-he-thong/thong-bao/index.tsx',
      },
      {
        id: 16011,
        name: 'Menu',
        type: 'MENU',
        label: 'Menu',
        route: 'menu',
        parentId: 1600,
        component: '/quan-tri-he-thong/menu/index.tsx',
      },
    ],
    parentId: '',
  },
];

export const UserPermissionData = [
  {
    order: 1,
    id: 1,
    parentId: '',
    label: 'Trang chủ',
    name: 'Trang chủ',
    icon: 'ion:home-outline',
    type: 'MENU',
    route: 'trang-chu',
    component: '/sys/trang-chu/index.tsx',
  },
  {
    order: 2,
    id: 2,
    parentId: '',
    label: 'Thu họ',
    name: 'Thu họ',
    icon: 'fa6-solid:sack-dollar',
    type: 'MENU',
    route: 'thu-ho',
    component: '/sys/thu-ho/index.tsx',
  },
];

export const InitRoleData: RoleData[] = [
  {
    name: RoleName.USER as string,
    permissions: UserPermissionData,
    level: 0,
    link:
      process.env.ENV_ENVIROMENT === 'prod'
        ? 'https://api.npoint.io/0f00514e47abd0de8b46'
        : 'https://api.npoint.io/21badbf7014749b1075c',
    id: RoleId.USER as string,
  },
  {
    name: RoleName.ADMIN as string,
    permissions: AdminPermissionData,
    level: 1,
    link:
      process.env.ENV_ENVIROMENT === 'prod'
        ? 'https://api.npoint.io/cbcfe2e40bd899644d60'
        : 'https://api.npoint.io/bd4baa497300c871605a',
    id: RoleId.ADMIN as string,
  },
  {
    name: RoleName.SUPER_ADMIN as string,
    permissions: SuperAdminPermissionData,
    level: 2,
    link:
      process.env.ENV_ENVIROMENT === 'prod'
        ? 'https://api.npoint.io/8e400ff7ff01cdcceba0'
        : 'https://api.npoint.io/5a33d550defe37a791a5',
    id: RoleId.SUPER_ADMIN as string,
  },
];
