import { RoleData, RoleId, RoleName } from './role.type';

export const SuperAdminPermissionData = [
  {
    order: 1,
    id: 1,
    parentId: '',
    label: 'Trang chủ',
    name: 'Trang chủ',
    icon: 'ion:home-outline',
    type: 'MENU',
    route: 'trang-chu',
    component: '/sys/trang-chu/index.tsx',
  },
  {
    order: 2,
    id: 2,
    parentId: '',
    label: 'Thu họ',
    name: 'Thu họ',
    icon: 'fa6-solid:sack-dollar',
    type: 'MENU',
    route: 'thu-ho',
    component: '/sys/thu-ho/index.tsx',
  },
  {
    order: 3,
    id: 3,
    parentId: '',
    label: 'Đóng họ hôm nay',
    name: 'Đóng họ hôm nay',
    icon: 'streamline:payment-10',
    type: 'MENU',
    route: 'dong-ho-hom-nay',
    component: '/sys/dong-ho-hom-nay/index.tsx',
  },
  {
    order: '4',
    id: 4,
    parentId: '',
    label: 'Cầm đồ',
    name: 'Cầm đồ',
    icon: 'akar-icons:money',
    type: 'MENU',
    route: 'cam-do',
    component: '/sys/cam-do/index.tsx',
  },
  // {
  //   "order": "6",
  //   "id": 6,
  //   "parentId": "",
  //   "label": "Nhắc nợ khách hàng",
  //   "name": "Nhắc nợ khách hàng",
  //   "icon": "simple-line-icons:call-out",
  //   "type": "MENU",
  //   "route": "nhac-no-khach-hang",
  //   "component": "/sys/nhac-no-khach-hang/index.tsx"
  // },
  {
    order: 9,
    id: 9,
    parentId: '',
    label: 'Quản lý khách hàng',
    name: 'Quản lý khách hàng',
    icon: 'fluent:people-money-20-filled',
    type: 'CATALOGUE',
    route: 'quan-ly-khach-hang',
    children: [
      {
        id: 91,
        parentId: 9,
        label: 'Danh sách khách hàng',
        name: 'Danh sách khách hàng',
        type: 'MENU',
        route: 'danh-sach-khach-hang',
        component: '/quan-ly-khach-hang/danh-sach-khach-hang/index.tsx',
      },
      {
        id: 9,
        parentId: 9,
        label: 'Danh sách nợ xấu',
        name: 'Danh sách nợ xấu',
        type: 'MENU',
        route: 'kiem-tra-no-xau',
        component: '/quan-ly-khach-hang/kiem-tra-no-xau/index.tsx',
      },
    ],
  },
  // {
  //   "order": 10,
  //   "id": 1000,
  //   "parentId": "",
  //   "label": "Quản lý đa cửa hàng",
  //   "name": "Quản lý đa cửa hàng",
  //   "icon": "streamline:shopping-store-2-store-shop-shops-stores",
  //   "type": "CATALOGUE",
  //   "route": "quan-ly-da-cua-hang",
  //   "children": [
  //     {
  //       "id": 10001,
  //       "parentId": 1000,
  //       "label": "Danh sách cửa hàng",
  //       "name": "Danh sách cửa hàng",
  //       "type": "MENU",
  //       "route": "danh-sach-cua-hang",
  //       "component": "/quan-ly-da-cua-hang/danh-sach-cua-hang/index.tsx"
  //     }
  //   ]
  // },
  {
    order: '12',
    id: 1200,
    parentId: '',
    label: 'Quản lý thu chi',
    name: 'Quản lý thu chi',
    icon: 'vaadin:money-exchange',
    type: 'CATALOGUE',
    route: 'quan-ly-thu-chi',
    children: [
      {
        id: 12001,
        parentId: 1200,
        label: 'Thu/Chi hợp đồng',
        name: 'Thu/Chi hợp đồng',
        type: 'MENU',
        route: 'thu-chi-hop-dong',
        component: '/quan-ly-thu-chi/thu-chi-hop-dong/index.tsx',
      },
      {
        id: 12002,
        parentId: 1200,
        label: 'Thu/Chi ngoài lề',
        name: 'Thu/Chi ngoài lề',
        type: 'MENU',
        route: 'thu-chi-ngoai-le',
        component: '/quan-ly-thu-chi/thu-chi-ngoai-le/index.tsx',
      },
      {
        id: 12003,
        parentId: 1200,
        label: 'Cấu hình thu chi',
        name: 'Cấu hình thu chi',
        type: 'MENU',
        route: 'cau-hinh-phan-loai',
        component: '/quan-ly-thu-chi/cau-hinh-phan-loai/index.tsx',
      },
    ],
  },
  {
    order: '14',
    id: 1400,
    parentId: '',
    label: 'Thống kê',
    name: 'Thống kê',
    icon: 'akar-icons:statistic-up',
    type: 'CATALOGUE',
    route: 'thong-ke',
    children: [
      {
        id: 14009,
        parentId: 1400,
        label: 'Tổng quan',
        name: 'Tổng quan',
        type: 'MENU',
        route: 'tong-quan',
        component: '/thong-ke/tong-quan/index.tsx',
      },
      {
        id: 14001,
        parentId: 1400,
        label: 'Thu dự kiến',
        name: 'Thu dự kiến',
        type: 'MENU',
        route: 'thu-du-kien',
        component: '/thong-ke/thu-du-kien/index.tsx',
      },
    ],
  },
  {
    order: '16',
    id: 1600,
    parentId: '',
    label: 'Quản trị hệ thống',
    name: 'Quản trị hệ thống',
    icon: 'grommet-icons:system',
    type: 'CATALOGUE',
    route: 'quan-tri-he-thong',
    children: [
      {
        id: 16001,
        parentId: 1600,
        label: 'Thiết lập thiết bị',
        name: 'Thiết lập thiết bị',
        type: 'MENU',
        route: 'cau-hinh-tai-san',
        component: '/quan-tri-he-thong/cau-hinh-tai-san/index.tsx',
      },
      {
        id: 16002,
        parentId: 1600,
        label: 'Thiết lập máy chủ',
        name: 'Thiết lập máy chủ',
        type: 'MENU',
        route: 'cau-hinh-tinh-lai',
        component: '/quan-tri-he-thong/cau-hinh-tinh-lai/index.tsx',
      },
      {
        id: 16012,
        parentId: 1600,
        label: 'Thiết lập loại tài sản',
        name: 'Thiết lập loại tài sản',
        type: 'MENU',
        route: 'thiet-lap-loai-tai-san',
        component: '/quan-tri-he-thong/thiet-lap-loai-tai-san/index.tsx',
      },
    ],
  },
  {
    order: '17',
    id: 1700,
    parentId: '',
    label: 'Báo cáo',
    name: 'Báo cáo',
    icon: 'mdi:report-line',
    type: 'CATALOGUE',
    route: 'bao-cao',
    children: [
      {
        id: 17001,
        parentId: 1700,
        label: 'Lợi nhuận',
        name: 'Lợi nhuận',
        type: 'MENU',
        route: 'loi-nhuan',
        component: '/bao-cao/loi-nhuan/index.tsx',
      },
    ],
  },
  {
    order: '18',
    id: 1800,
    parentId: '',
    label: 'Quản lý',
    name: 'Quản lý',
    icon: 'hugeicons:security-validation',
    type: 'CATALOGUE',
    route: 'quan-ly',
    children: [
      {
        id: 18001,
        parentId: 1800,
        label: 'Quyền truy cập',
        name: 'Quyền truy cập',
        type: 'MENU',
        route: 'quyen-truy-cap',
        component: '/phan-quyen/quyen-truy-cap/index.tsx',
      },
      {
        id: 18002,
        parentId: 1800,
        label: 'Vai trò',
        name: 'Vai trò',
        type: 'MENU',
        route: 'chuc-nang',
        component: '/phan-quyen/vai-tro/index.tsx',
      },
    ],
  },
];

export const AdminPermissionData = [
  {
    order: 1,
    id: 1,
    parentId: '',
    label: 'Trang chủ',
    name: 'Trang chủ',
    icon: 'ion:home-outline',
    type: 'MENU',
    route: 'trang-chu',
    component: '/sys/trang-chu/index.tsx',
  },
  {
    order: 2,
    id: 2,
    parentId: '',
    label: 'Thu họ',
    name: 'Thu họ',
    icon: 'fa6-solid:sack-dollar',
    type: 'MENU',
    route: 'thu-ho',
    component: '/sys/thu-ho/index.tsx',
  },
  {
    order: 3,
    id: 3,
    parentId: '',
    label: 'Đóng họ hôm nay',
    name: 'Đóng họ hôm nay',
    icon: 'streamline:payment-10',
    type: 'MENU',
    route: 'dong-ho-hom-nay',
    component: '/sys/dong-ho-hom-nay/index.tsx',
  },
  {
    order: '4',
    id: 4,
    parentId: '',
    label: 'Cầm đồ',
    name: 'Cầm đồ',
    icon: 'akar-icons:money',
    type: 'MENU',
    route: 'cam-do',
    component: '/sys/cam-do/index.tsx',
  },
  // {
  //   "order": "6",
  //   "id": 6,
  //   "parentId": "",
  //   "label": "Nhắc nợ khách hàng",
  //   "name": "Nhắc nợ khách hàng",
  //   "icon": "simple-line-icons:call-out",
  //   "type": "MENU",
  //   "route": "nhac-no-khach-hang",
  //   "component": "/sys/nhac-no-khach-hang/index.tsx"
  // },
  {
    order: 9,
    id: 9,
    parentId: '',
    label: 'Quản lý khách hàng',
    name: 'Quản lý khách hàng',
    icon: 'fluent:people-money-20-filled',
    type: 'CATALOGUE',
    route: 'quan-ly-khach-hang',
    children: [
      {
        id: 91,
        parentId: 9,
        label: 'Danh sách khách hàng',
        name: 'Danh sách khách hàng',
        type: 'MENU',
        route: 'danh-sach-khach-hang',
        component: '/quan-ly-khach-hang/danh-sach-khach-hang/index.tsx',
      },
      {
        id: 9,
        parentId: 9,
        label: 'Danh sách nợ xấu',
        name: 'Danh sách nợ xấu',
        type: 'MENU',
        route: 'kiem-tra-no-xau',
        component: '/quan-ly-khach-hang/kiem-tra-no-xau/index.tsx',
      },
    ],
  },
  // {
  //   "order": 10,
  //   "id": 1000,
  //   "parentId": "",
  //   "label": "Quản lý đa cửa hàng",
  //   "name": "Quản lý đa cửa hàng",
  //   "icon": "streamline:shopping-store-2-store-shop-shops-stores",
  //   "type": "CATALOGUE",
  //   "route": "quan-ly-da-cua-hang",
  //   "children": [
  //     {
  //       "id": 10001,
  //       "parentId": 1000,
  //       "label": "Danh sách cửa hàng",
  //       "name": "Danh sách cửa hàng",
  //       "type": "MENU",
  //       "route": "danh-sach-cua-hang",
  //       "component": "/quan-ly-da-cua-hang/danh-sach-cua-hang/index.tsx"
  //     }
  //   ]
  // },
  {
    order: '12',
    id: 1200,
    parentId: '',
    label: 'Quản lý thu chi',
    name: 'Quản lý thu chi',
    icon: 'vaadin:money-exchange',
    type: 'CATALOGUE',
    route: 'quan-ly-thu-chi',
    children: [
      {
        id: 12001,
        parentId: 1200,
        label: 'Thu/Chi hợp đồng',
        name: 'Thu/Chi hợp đồng',
        type: 'MENU',
        route: 'thu-chi-hop-dong',
        component: '/quan-ly-thu-chi/thu-chi-hop-dong/index.tsx',
      },
      {
        id: 12002,
        parentId: 1200,
        label: 'Thu/Chi ngoài lề',
        name: 'Thu/Chi ngoài lề',
        type: 'MENU',
        route: 'thu-chi-ngoai-le',
        component: '/quan-ly-thu-chi/thu-chi-ngoai-le/index.tsx',
      },
      {
        id: 12003,
        parentId: 1200,
        label: 'Cấu hình thu chi',
        name: 'Cấu hình thu chi',
        type: 'MENU',
        route: 'cau-hinh-phan-loai',
        component: '/quan-ly-thu-chi/cau-hinh-phan-loai/index.tsx',
      },
    ],
  },
  {
    order: '14',
    id: 1400,
    parentId: '',
    label: 'Thống kê',
    name: 'Thống kê',
    icon: 'akar-icons:statistic-up',
    type: 'CATALOGUE',
    route: 'thong-ke',
    children: [
      {
        id: 14009,
        parentId: 1400,
        label: 'Tổng quan',
        name: 'Tổng quan',
        type: 'MENU',
        route: 'tong-quan',
        component: '/thong-ke/tong-quan/index.tsx',
      },
      {
        id: 14001,
        parentId: 1400,
        label: 'Thu dự kiến',
        name: 'Thu dự kiến',
        type: 'MENU',
        route: 'thu-du-kien',
        component: '/thong-ke/thu-du-kien/index.tsx',
      },
    ],
  },
  {
    order: '16',
    id: 1600,
    parentId: '',
    label: 'Quản trị hệ thống',
    name: 'Quản trị hệ thống',
    icon: 'grommet-icons:system',
    type: 'CATALOGUE',
    route: 'quan-tri-he-thong',
    children: [
      {
        id: 16001,
        parentId: 1600,
        label: 'Thiết lập thiết bị',
        name: 'Thiết lập thiết bị',
        type: 'MENU',
        route: 'cau-hinh-tai-san',
        component: '/quan-tri-he-thong/cau-hinh-tai-san/index.tsx',
      },
      {
        id: 16002,
        parentId: 1600,
        label: 'Thiết lập máy chủ',
        name: 'Thiết lập máy chủ',
        type: 'MENU',
        route: 'cau-hinh-tinh-lai',
        component: '/quan-tri-he-thong/cau-hinh-tinh-lai/index.tsx',
      },
      {
        id: 16012,
        parentId: 1600,
        label: 'Thiết lập loại tài sản',
        name: 'Thiết lập loại tài sản',
        type: 'MENU',
        route: 'thiet-lap-loai-tai-san',
        component: '/quan-tri-he-thong/thiet-lap-loai-tai-san/index.tsx',
      },
    ],
  },
  {
    order: '17',
    id: 1700,
    parentId: '',
    label: 'Báo cáo',
    name: 'Báo cáo',
    icon: 'mdi:report-line',
    type: 'CATALOGUE',
    route: 'bao-cao',
    children: [
      {
        id: 17001,
        parentId: 1700,
        label: 'Lợi nhuận',
        name: 'Lợi nhuận',
        type: 'MENU',
        route: 'loi-nhuan',
        component: '/bao-cao/loi-nhuan/index.tsx',
      },
    ],
  },
  {
    order: '18',
    id: 1800,
    parentId: '',
    label: 'Quản lý',
    name: 'Quản lý',
    icon: 'hugeicons:security-validation',
    type: 'CATALOGUE',
    route: 'quan-ly',
    children: [
      {
        id: 18001,
        parentId: 1800,
        label: 'Quyền truy cập',
        name: 'Quyền truy cập',
        type: 'MENU',
        route: 'quyen-truy-cap',
        component: '/phan-quyen/quyen-truy-cap/index.tsx',
      },
      {
        id: 18002,
        parentId: 1800,
        label: 'Vai trò',
        name: 'Vai trò',
        type: 'MENU',
        route: 'chuc-nang',
        component: '/phan-quyen/vai-tro/index.tsx',
      },
    ],
  },
];

export const UserPermissionData = [
  {
    order: 1,
    id: 1,
    parentId: '',
    label: 'Trang chủ',
    name: 'Trang chủ',
    icon: 'ion:home-outline',
    type: 'MENU',
    route: 'trang-chu',
    component: '/sys/trang-chu/index.tsx',
  },
  {
    order: 2,
    id: 2,
    parentId: '',
    label: 'Thu họ',
    name: 'Thu họ',
    icon: 'fa6-solid:sack-dollar',
    type: 'MENU',
    route: 'thu-ho',
    component: '/sys/thu-ho/index.tsx',
  },
  {
    order: 3,
    id: 3,
    parentId: '',
    label: 'Đóng họ hôm nay',
    name: 'Đóng họ hôm nay',
    icon: 'streamline:payment-10',
    type: 'MENU',
    route: 'dong-ho-hom-nay',
    component: '/sys/dong-ho-hom-nay/index.tsx',
  },
  {
    order: '4',
    id: 4,
    parentId: '',
    label: 'Cầm đồ',
    name: 'Cầm đồ',
    icon: 'akar-icons:money',
    type: 'MENU',
    route: 'cam-do',
    component: '/sys/cam-do/index.tsx',
  },
];

export const InitRoleData: RoleData[] = [
  {
    name: RoleName.USER as string,
    permissions: UserPermissionData,
    level: 0,
    link:
      process.env.ENV_ENVIROMENT === 'prod'
        ? 'https://api.npoint.io/0f00514e47abd0de8b46'
        : 'https://api.npoint.io/21badbf7014749b1075c',
    id: RoleId.USER as string,
  },
  {
    name: RoleName.ADMIN as string,
    permissions: AdminPermissionData,
    level: 1,
    link:
      process.env.ENV_ENVIROMENT === 'prod'
        ? 'https://api.npoint.io/cbcfe2e40bd899644d60'
        : 'https://api.npoint.io/bd4baa497300c871605a',
    id: RoleId.ADMIN as string,
  },
  {
    name: RoleName.SUPER_ADMIN as string,
    permissions: SuperAdminPermissionData,
    level: 2,
    link:
      process.env.ENV_ENVIROMENT === 'prod'
        ? 'https://api.npoint.io/8e400ff7ff01cdcceba0'
        : 'https://api.npoint.io/5a33d550defe37a791a5',
    id: RoleId.SUPER_ADMIN as string,
  },
];
